Repository fga-eps-mds/2020-2-SiGeD-Frontend, pull requests merged in 2021-04, with the labels that each got.

#54 Criar filtro de demandas pelo nome do cliente
  src/Components/ClientProfileData/index.js
  src/Components/DemandData/index.js
  src/Pages/ClientListScreen/index.js
  src/Pages/ListDemandsScreen/index.js
  src/Services/Axios/demandsServices.js
Labels: Minor Release

#60 Editar e deletar atualização da demanda
  package.json
  src/Components/ModalEditUpdateDemand/index.js
  src/Components/NewUpdateCard/Style.js
  src/Components/NewUpdateCard/index.js
  src/Components/UpdateCard/Style.js
  src/Components/UpdateCard/index.js
  src/Pages/ViewDemandsScreen/index.js
  src/Services/Axios/demandsServices.js
Labels: Minor Release

#57 Restringir a visualização de uma atualização para somente um setor
  src/Components/ModalEditUpdateDemand/index.js
  src/Components/NewUpdateCard/index.js
  src/Components/UpdateCard/Style.js
  src/Components/UpdateCard/index.js
  src/Components/ViewDemandCard/index.js
  src/Components/ViewDemandSidebar/index.js
  src/Pages/ViewDemandsScreen/index.js
Labels: Minor Release

#58 [174] Atualizando o nome do projeto
  README.md
  package.json
Labels: Not a Release

#63 PR template
  .github/PULL_REQUEST_TEMPLATE.MD
  scripts/consts.js
Labels: Not a Release

#62 Filtro de ano na tela de demandas
  src/Pages/ListDemandsScreen/Style.js
  src/Pages/ListDemandsScreen/index.js
  src/Services/Axios/demandsServices.js
Labels: Minor Release

#61 Filtro de categorias
  src/Pages/ListDemandsScreen/index.js
Labels: Minor Release

#67 [199] Enviar senha temporária
  src/Components/UserForms/index.js
  src/Context/index.js
  src/Pages/ChangePasswordScreen/Style.js
  src/Pages/ChangePasswordScreen/index.js
  src/Pages/LoginScreen/index.js
  src/Pages/RecoverPasswordScreen/Style.js
  src/Pages/RecoverPasswordScreen/index.js
  src/Pages/RegisterScreen/index.js
  src/Pages/UserUpdateScreen/index.js
  src/Routes/ChangePassRoutes.js
  src/Routes/OtherRoutes.js
  src/Routes/SignInRoutes.js
  src/Routes/index.js
  src/Services/Axios/userServices.js
  src/Utils/validations.js
Labels: Minor Release

#66 Insere novas modais e melhorias no código.
  src/Components/AddCategoryComponent/index.js
  src/Components/CategoriesData/index.js
  src/Components/ClientProfileData/index.js
  src/Components/CloseDemandModal/index.js
  src/Components/ConfirmDemandModal/index.js
  src/Components/DataList/index.js
  src/Components/ModalComp/index.js
  src/Components/ModalEditUpdateDemand/index.js
  src/Components/ModalMessage/index.js
  src/Components/NavbarComp/index.js
  src/Components/NewUpdateCard/index.js
  src/Components/PersonalData/Style.js
  src/Components/PersonalData/index.js
  src/Components/SectorDropdown/index.js
  src/Components/SendDemandModal/index.js
  src/Components/UpdateCard/index.js
  src/Components/UserForms/index.js
  src/Context/index.js
  src/Pages/ClientListScreen/index.js
  src/Pages/ClientProfileScreen/index.js
  src/Pages/ClientRegisterScreen/index.js
  src/Pages/ClientUpdateScreen/index.js
  src/Pages/CreateDemandsScreen/index.js
  src/Pages/ListCategories/index.js
  src/Pages/ListDemandsScreen/index.js
  src/Pages/ListScreen/index.js
  src/Pages/ListSectors/index.js
  src/Pages/RegisterScreen/index.js
  src/Pages/UpdateDemandScreen/index.js
  src/Pages/UserUpdateScreen/index.js
  src/Pages/ViewDemandsScreen/index.js
  src/Services/Axios/clientServices.js
  src/Services/Axios/demandsServices.js
  src/Services/Axios/sectorServices.js
  src/Services/Axios/userServices.js
Labels: bug

#68 Gráfico de demandas
  package.json
  src/Components/NavbarComp/index.js
  src/Pages/StatisticsScreen/Style.js
  src/Pages/StatisticsScreen/index.js
  src/Routes/OtherRoutes.js
  src/Services/Axios/demandsServices.js
Labels: Minor Release

#69 Adicionando badge
  README.md
Labels: Not a Release

#80 Fix script de release
  scripts/consts.js
Labels: Not a Release

#72 Filtro de anos no prontuario do cliente
  src/Components/GenericListScreen/Style.js
  src/Components/GenericListScreen/index.js
  src/Pages/ClientProfileScreen/Style.js
  src/Pages/ClientProfileScreen/index.js
  src/Pages/ListDemandsScreen/Style.js
  src/Pages/ListDemandsScreen/index.js
Labels: Minor Release

#74 Criar alertas de demandas
  src/Components/CreateAlertModal/Style.js
  src/Components/CreateAlertModal/index.js
  src/Components/SelectedCategories/Style.js
  src/Components/ViewDemandSidebar/Style.js
  src/Components/ViewDemandSidebar/index.js
  src/Services/Axios/demandsServices.js
Labels: Minor Release

#78 Historia da demanda e cliente
  src/Components/ClientHistory/Style.js
  src/Components/ClientHistory/index.js
  src/Components/DemandHistory/Style.js
  src/Components/DemandHistory/index.js
  src/Components/ModalHistory/index.js
  src/Components/ProfileSidebarComponent/Style.js
  src/Components/ProfileSidebarComponent/index.js
  src/Components/ViewDemandSidebar/Style.js
  src/Components/ViewDemandSidebar/index.js
  src/Pages/ClientProfileScreen/index.js
  src/Pages/ClientRegisterScreen/index.js
  src/Pages/ClientUpdateScreen/index.js
  src/Pages/CreateDemandsScreen/index.js
  src/Pages/ViewDemandsScreen/index.js
  src/Services/Axios/clientServices.js
Labels: Minor Release
